### ISSUE TITLE
Global class under test object

### ISSUE THREAD

**Issue by ziobron** [piotrku91/university-db#2]
https://github.com/piotrku91/university-db/blob/b01edb232c0ac8cc260dcd767b52657ba28c52ae/test.cpp#L5

Tests should be independent of each other. You can check that they are by shuffling them. 
Generally, it is preferred to create structure and use it as a test fixture (TEST_F). Thanks to that we start each test with a clear state and we don't have dependencies on other tests.

It will be described in GTest lessons.

**Comment by piotrku91** [comment]
Thanks for idea. I rechecked GTest lessons.All new changes I will push to new_tasks branch https://github.com/piotrku91/university-db/tree/new_tasks.
