### ISSUE TITLE
Raw pointers to unique_ptr - avoid it

### ISSUE THREAD

**Issue by ziobron** [piotrku91/university-db#6]
https://github.com/piotrku91/university-db/blob/b01edb232c0ac8cc260dcd767b52657ba28c52ae/Db.hpp#L14-L16

There is no use in creating raw ptrs to unique_ptr. Just use shared_ptrs everywhere. 
I also think that `IndexOfStudentIdxs_` and `IndexOfStudentPesels_` are really not necessary and they make things more complex.

**Comment by piotrku91** [comment]
I replaced all std::unique_ptr<Student>* to shared_ptrs and all tests passed so I think that fix is done. All new changes I will push to new_tasks branch [https://github.com/piotrku91/university-db/tree/new_tasks](url) . 

I created IndexOfStudentIdxs_ and IndexOfStudentPesels_ for implement binary search to database in easy way.  I think is not so bad idea :)
