### ISSUE TITLE
Misuse of unique_ptrs

### ISSUE THREAD

**Issue by ziobron** [piotrku91/university-db#7]
https://github.com/piotrku91/university-db/blob/b01edb232c0ac8cc260dcd767b52657ba28c52ae/Db.hpp#L17

This program should be checked for memory leaks. 
Generally, you should not overuse unique_ptrs in such "database" solutions. Shared_ptrs usage is recommended. You want to share your data eg. by exporting it from the database.

**Comment by piotrku91** [comment]
It was a temporary function from very basic version of database. I removed this solution.
