### ISSUE TITLE
Change declaration of copy constructor

### ISSUE THREAD

**Issue by ziobron** [piotrku91/university-db#8]
https://github.com/piotrku91/university-db/blob/b01edb232c0ac8cc260dcd767b52657ba28c52ae/Db.hpp#L51

`Db(const Db&) = delete;` - this is the proper way to declate a copy constructor.
You should also delete the copy assignment operator `Db& operator=(const Db&) = delete;`

**Comment by piotrku91** [comment]
Thanks for solution and help. I fix it.
