### ISSUE TITLE
Change the return type

### ISSUE THREAD

**Issue by ziobron** [piotrku91/university-db#9]
https://github.com/piotrku91/university-db/blob/b01edb232c0ac8cc260dcd767b52657ba28c52ae/Db.hpp#L36-L39

It returns a raw pointer to unique_ptr. Something that we want to avoid. 
You can return an iterator, raw pointer, or shared_ptr.

**Comment by piotrku91** [comment]
I replaced all std::unique_ptr<Student>* to shared_ptrs and all tests passed so I think that fix is done. All new changes I will push to new_tasks branch [https://github.com/piotrku91/university-db/tree/new_tasks](url) . Thanks for help.
